### PR TITLE
Fix incorrect Lapotron Crystal crafting recipe

### LINKED ISSUE #1336: [BUG] Lapotron Crystals craft to wrong maximum charge.
**Describe the bug**
In #1189, the maximum charge of the Lapotron Crystals was increased to 10M EU. However, the crafting recipe still crafts to Lapotron crystals with 4M EU Maximum charge.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.596
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Look at the Lapotron crystal recipe in JEI and see that it has 10M EU max charge.
2) Look at the crafting recipe and see that it crafts to one with 4M EU max charge

**Expected behavior**
To craft to 10M EU maximum charge

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
**What:**
This PR fixes the incorrect Lapotron Crystal crafting recipe, where the Lapotron Crystal had a capacity of 10M EU, but the crafting recipe only crafted to one with 4M EU.

**How solved:**
A new method was added, which takes an additional parameter of the maximum charge, which then sets the output of the crafting recipe to have a maximum charge of that amount. This is used in conjunction with a new helper method in `MetaItem` that will return the maximum charge of an electric item.

**Outcome:**
Fixes Lapotron Crystal crafting to one with incorrect EU capacity. Closes #1336.

**Additional info:**

This is the case for all variants of the Lapotron, they craft to the correct amount

**Possible compatibility issue:**
None expected

### CODE REVIEW

File: src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java [hunk 1]
```diff
@@ -90,7 +90,7 @@ private static void loadCraftingRecipes() {
         for(Material material : new Material[] {Materials.Lapis, Materials.Lazurite, Materials.Sodalite}) {
             String recipeName = "lapotron_crystal_" + material.toString();
             ModHandler.addShapedEnergyTransferRecipe(recipeName, MetaItems.LAPOTRON_CRYSTAL.getStackForm(),
-                Ingredient.fromStacks(MetaItems.ENERGY_CRYSTAL.getStackForm()), false,
+                Ingredient.fromStacks(MetaItems.LAPOTRON_CRYSTAL.getStackForm()), MetaItems.LAPOTRON_CRYSTAL.getChargeAmount(), false,
```
Comment (LAGIdiot) [inline src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java:93]: You need to pass in info from which items it is crafted so it can transfer energy from them - right now it just wastes energy from ENERGY_CRYSTAL

File: src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java [hunk 2]
```diff
@@ -25,13 +25,31 @@ public ShapedOreEnergyTransferRecipe(ResourceLocation group, @Nonnull ItemStack
...
         this.transferMaxCharge = transferMaxCharge;
         fixOutputItemMaxCharge();
     }
 
+    public ShapedOreEnergyTransferRecipe(ResourceLocation group, @Nonnull ItemStack result, Predicate<ItemStack> chargePredicate, long chargeAmount, boolean transferMaxCharge, ShapedPrimer primer) {
+        super(group, result, primer);
+        this.chargePredicate = chargePredicate;
+        this.transferMaxCharge = transferMaxCharge;
+        setMaxChargeInRecipe(chargeAmount);
+    }
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java:44]: This is wrong you are overriding crafted item max charge to it's max charge. This will produce unnecessary NBT mess and use calculation time.
For this case we should just not call `fixOutputItemMaxCharge` which means no override which means default max energy level of item is used

File: src/main/java/gregtech/api/recipes/ModHandler.java [hunk 3]
```diff
@@ -278,6 +278,25 @@ public static void addShapedEnergyTransferRecipe(String regName, ItemStack resul
...
+            RecipeMap.setFoundInvalidRecipe(true);
+            return;
+        }
+
+        IRecipe shapedOreRecipe = new ShapedOreEnergyTransferRecipe(null, result.copy(), chargePredicate, chargeAmount, transferMaxCharge, finalizeShapedRecipeInput(recipe))
+            .setMirrored(false) //make all recipes not mirrored by default
+            .setRegistryName(regName);
+        ForgeRegistries.RECIPES.register(shapedOreRecipe);
+    }
+
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/recipes/ModHandler.java:299]: This is nearly 100% code duplication except one param in method header and then passing it. This could be done by extending current one by that param and its passing down. And creating new function with old param set which just calls that updated one.

**Review by LAGIdiot — CHANGES_REQUESTED** [review]
Thank you for creating this PR. There are some problems with it so please see to them

File: src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java (hunk 1 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java]: This has been fixed.

File: src/main/java/gregtech/api/recipes/ModHandler.java (hunk 3 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/recipes/ModHandler.java]: I have done so

File: src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java (hunk 2 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java]: This is now done. A boolean is passed in for the new method to determine if `fixOutputItemMaxCharge` will be called, with all the old recipes having this boolean as true by default due to a redirected method.

File: src/main/java/gregtech/api/items/metaitem/MetaItem.java [hunk 4]
```diff
@@ -835,6 +835,16 @@ public ItemStack getChargedStack(long chargeAmount) {
...
+        public long getChargeAmount() {
+            ItemStack itemstack = getStackForm(1);
+            IElectricItem electricItem = itemstack.getCapability(GregtechCapabilities.CAPABILITY_ELECTRIC_ITEM, null);
+            if(electricItem == null) {
+                throw new IllegalStateException("Not an electric item");
+            }
+
+            return electricItem.getMaxCharge();
+        }
+
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/items/metaitem/MetaItem.java:847]: I don't think this is needed anymore

File: src/main/java/gregtech/api/recipes/ModHandler.java [hunk 5]
```diff
@@ -260,6 +260,10 @@ public static void addShapedRecipe(String regName, ItemStack result, Object... r
     }
 
     public static void addShapedEnergyTransferRecipe(String regName, ItemStack result, Predicate<ItemStack> chargePredicate, boolean transferMaxCharge, Object... recipe) {
+        addShapedEnergyTransferRecipeWithOverride(regName, result, chargePredicate, true, transferMaxCharge, recipe);
+    }
+
+    public static void addShapedEnergyTransferRecipeWithOverride(String regName, ItemStack result, Predicate<ItemStack> chargePredicate, boolean overrideCharge, boolean transferMaxCharge, Object... recipe) {
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/recipes/ModHandler.java:266]: I am not fond of this name but I understand why you named this function differently.
But I am not getting any idea for better method name myself.

**Review by LAGIdiot — CHANGES_REQUESTED** [review]
Good work on this PR. There are few last comments then needs to be addressed and then it should be finished.

File: src/main/java/gregtech/api/items/metaitem/MetaItem.java (hunk 4 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/items/metaitem/MetaItem.java]: I have removed it

File: src/main/java/gregtech/api/recipes/ModHandler.java (hunk 5 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/recipes/ModHandler.java:266]: If you think of a better name, let me know and I will change it

Comment (LAGIdiot) [reply src/main/java/gregtech/api/recipes/ModHandler.java:266]: Fair enough, let's go with current one.

**Review by LAGIdiot — APPROVED** [review]
