### PR TITLE
Fix Multiblocks voiding partial multi item outputs when output is mostly Full

### LINKED ISSUE #1332: [BUG] Multismelter can void items due to coil bonus
**Describe the bug**
The Multismelter can void items due to the coil bonus and having only a single output slot open.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.594
_Modpack:_ None
_Addons:_ SoG 2.15

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Create a multismelter. I used IV input and output buses to get a large enough output slot. Additionally, I used fusion coils since they have a very large item smelting bonus to easily reproduce this issue.
2) Using Sand (or any other smeltable item), smelt it in the mutlismelter to fill the output bus with glass.
3) Add in two stacks of sand to the input bus of the multismelter.
4) Remove one stack of glass from the item output bus of the multismelter. 
5) See that the multismelter consumes both of the stack of sand in the input bus (due to the coil bonus) but only 1 stack gets put in the output bus, due to only having space for 1 stack.

**Expected behavior**
For the Multismelter not to function if there is not enough room in the output bus for all items smelted, including those added by the coil bonus

**Additional Information**
Attached GIF to demonstrate the issue

### LINKED ISSUE #1334: [BUG] Output voiding for multi item output recipes is possible with GTCE mutliblocks
**Describe the bug**
It is possible to void part of an output from a recipe that has multiple item outputs in several GTCE multiblocks. The voiding occurs when having only 1 free slot in the output bus. The recipe will run once, fill the empty slot in the output bus with the first output from the recipe and void the other outputs from the recipe. Then the multiblock will stop running due to not having room for both item outputs. This has been tested with the blast furnace and the Implosion compressor.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.594
_Modpack:_ None
_Addons:_ SoG 2.15

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Construct a Electric Blast Furnace, and use an LV item output to quickly reproduce the issue
2) Using the Ruby Dust recipe (1 ruby dust -> 5 aluminum nuggets + 4 tiny pile of dark ash), run the EBF until there are 2 slots of the LV item output occupied by the aluminum dust and 1 slot occupied by the dark ash. Make sure that all the stacks of these items are full stacks.
3) Place in 2 more ruby dust (2 recipes)
4) Notice that the recipe will be run once, and that 5 aluminum nuggets will be added to the open slot in the output bus, but the dark ash will be voided. And also notice that the EBF will not process the second recipe, because the output bus does not have room.

This can be repeated in the Implosion Compressor, and was repeated using the topaz dust to topaz gem recipe.

**Expected behavior**
For the mutliblock not to run if there is not room in the output bus for all the outputs of the recipe.

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
**What:**
This PR fixes multiblocks voiding parts of multi item outputs when the output bus only has room for the first output of the recipe.

**How solved:**
This PR adds logic and methods checking if the output of recipes can merge into available slots in the output bus to prevent the issue of output voiding due to checking each item individually, which missed out on possible output inventory changes, causing some portions of the output to be voided.

**Outcome:**
Fixes Multiblocks voiding partial recipe outputs when output bus is mostly full. Closes #1334. Closes #1332. Supersedes #1333.

**Possible compatibility issue:**
The old method was redirected to the new method, so there should be minimal chance for compatibility issues.

### CODE REVIEW

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 1]
```diff
@@ -54,12 +55,40 @@ protected IMultipleTankHandler getOutputTank() {
...
+        int[] resultOverclock = calculateOverclock(recipe.getEUt(), getMaxVoltage(), recipe.getDuration());
+        int totalEUt = resultOverclock[0] * resultOverclock[1];
+        IItemHandlerModifiable importInventory = getInputInventory();
+        IItemHandlerModifiable exportInventory = getOutputInventory();
+        IMultipleTankHandler importFluids = getInputTank();
+        IMultipleTankHandler exportFluids = getOutputTank();
+        return (totalEUt >= 0 ? getEnergyStored() >= (totalEUt > getEnergyCapacity() / 2 ? resultOverclock[0] : totalEUt) :
+            (getEnergyStored() - resultOverclock[0] <= getEnergyCapacity())) &&
+            MetaTileEntity.addItemsToItemHandler(exportInventory, true, recipe.getAllItemOutputs(exportInventory.getSlots())) &&
+            recipe.getAllItemOutputs(exportInventory.getSlots()).size() <= getFreeSlots(exportInventory) &&
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:75]: These two same calls to `recipe.getAllItemOutputs` should be consolidated to one before return and values from it used here.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 2]
```diff
@@ -54,12 +55,40 @@ protected IMultipleTankHandler getOutputTank() {
...
+            MetaTileEntity.addFluidsToFluidHandler(exportFluids, true, recipe.getFluidOutputs()) &&
+            recipe.matches(true, importInventory, importFluids);
+    }
+
+    //Determines the number of free slots in the paseed inventory
+    protected int getFreeSlots(IItemHandlerModifiable inventory) {
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:81]: This name `getFreeSlots` does not sound correct to me as it does not return free slots but just number of them.
Maybe it should go even to utils as it is not something specific for this and anyone could use it then.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 3]
```diff
@@ -54,12 +55,40 @@ protected IMultipleTankHandler getOutputTank() {
...
+        IMultipleTankHandler exportFluids = getOutputTank();
+        return (totalEUt >= 0 ? getEnergyStored() >= (totalEUt > getEnergyCapacity() / 2 ? resultOverclock[0] : totalEUt) :
+            (getEnergyStored() - resultOverclock[0] <= getEnergyCapacity())) &&
+            MetaTileEntity.addItemsToItemHandler(exportInventory, true, recipe.getAllItemOutputs(exportInventory.getSlots())) &&
+            recipe.getAllItemOutputs(exportInventory.getSlots()).size() <= getFreeSlots(exportInventory) &&
+            MetaTileEntity.addFluidsToFluidHandler(exportFluids, true, recipe.getFluidOutputs()) &&
+            recipe.matches(true, importInventory, importFluids);
+    }
+
+    //Determines the number of free slots in the paseed inventory
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:80]: Typo in `paseed`. But this comment won't be needed when that functions is that short with really descriptive name

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 1 above)
Comment (LAGIdiot) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:75]: Also there is more elaborate logic required as you need to know number of slots you can put items in to and their capacity. 

For example when I build Implosion compressor. With LV Output bus (4 slots) and I let process 4x Amethyst Dust + 2x TNT => 3x Amethyst + 2x Tiny Pile of Dark Ashes it will only process 22x and then stop even if there is still capacity in output for another 10 runs.

**Review by LAGIdiot — CHANGES_REQUESTED** [review]
Thank you for creating this PR. There few things that needs to be sorted out.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 2 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java]: I have adjusted the name of the function. Let me know if it should be adjusted further.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 1 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java]: There has been a refactor to catch this case. Now the recipe output will attempt to merge into the existing stacks in the output bus before attempting to add the recipe output items to empty slots in the output bus. The above issue no longer exists, and the voiding issue is also solved.

File: src/main/java/gregtech/api/util/InventoryUtils.java [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+        }
+
+        // Deep copy the recipe output itemstacks
+        List<ItemStack> itemStackList = new ArrayList<>(items.size());
+        for(ItemStack i : items) {
+            itemStackList.add(i.copy());
+        }
+
+        // Sort by the number of items in each stack so we merge smallest stacks first.
+        itemStackList.sort((i,j) -> Integer.compare(i.getCount(), j.getCount()));
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/util/InventoryUtils.java:52]: I think we should use comparator here so it can be more readable.

File: src/main/java/gregtech/api/util/InventoryUtils.java [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+
+        // Deep copy the contents of the output bus
+        int numSlots = inventory.getSlots();
+        List<ItemStack> inventoryStacks = new ArrayList<>(numSlots);
+        for(int slotIndex = 0; slotIndex < numSlots; slotIndex++) {
+            ItemStack stack = inventory.getStackInSlot(slotIndex);
+            if(!stack.isEmpty())
+                inventoryStacks.add(stack.copy());
+        }
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/util/InventoryUtils.java:61]: This should be extracted to own method so there is not such complexity

File: src/main/java/gregtech/api/util/InventoryUtils.java [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+
+        // Since we're mutating the collection during iteration, use an iterator.
+        Iterator<ItemStack> outIter = itemStackList.iterator();
+        while(outIter.hasNext()) {
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/util/InventoryUtils.java:65]: I had quite hard time reading this. Is it really easiest way how to do this?

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 7]
```diff
@@ -54,12 +60,29 @@ protected IMultipleTankHandler getOutputTank() {
...
 
+    //Logic Mostly copied from AbstractRecipeLogic, but with some additional checking for Multiblock output spacing to prevent voiding
+    protected boolean multiBlockSetupAndConsumeRecipeInputs(Recipe recipe) {
+        int[] resultOverclock = calculateOverclock(recipe.getEUt(), getMaxVoltage(), recipe.getDuration());
+        int totalEUt = resultOverclock[0] * resultOverclock[1];
+        IItemHandlerModifiable importInventory = getInputInventory();
+        IItemHandlerModifiable exportInventory = getOutputInventory();
+        IMultipleTankHandler importFluids = getInputTank();
+        IMultipleTankHandler exportFluids = getOutputTank();
+        List<ItemStack> itemOutputs = recipe.getAllItemOutputs(exportInventory.getSlots());
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:77]: This can still void items if for example you use same recipe as before and you have only Export Bus with 1 slot. Then recipe will process but it will gave only Amethyst and void Tiny Pile of Dark Ashes. Which is probably not something we want

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 8]
```diff
@@ -54,12 +60,29 @@ protected IMultipleTankHandler getOutputTank() {
...
+        return (totalEUt >= 0 ? getEnergyStored() >= (totalEUt > getEnergyCapacity() / 2 ? resultOverclock[0] : totalEUt) :
+            (getEnergyStored() - resultOverclock[0] <= getEnergyCapacity())) &&
+            MetaTileEntity.addItemsToItemHandler(exportInventory, true, itemOutputs) &&
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:80]: I took another look at this and this function does exactly what you are doing with new one. But this one does not work correctly when more then one item is given and it takes up last available slot. As it simulates input for every item one by one without considering others.
I think we should fix this function not creating new one that does same thing. But we sure can use knowledge obtained when designing new merge function.

**Review by LAGIdiot — CHANGES_REQUESTED** [review]
Thank you for updating this PR. I give it another look and there are sine new insights and comments from me so please take a look at them

File: src/main/java/gregtech/api/util/InventoryUtils.java (hunk 6 above)
Comment (Exaxxion) [reply src/main/java/gregtech/api/util/InventoryUtils.java:65]: If one wishes to change the contents of a collection while they are iterating through it, the only safe way to do so is with `Iterator#remove()`, otherwise you will get a `ConcurrentModificationException`.

File: src/main/java/gregtech/api/util/InventoryUtils.java (hunk 4 above)
Comment (Exaxxion) [reply src/main/java/gregtech/api/util/InventoryUtils.java:52]: That one's on me, I was writing the snippet in a plaintext editor and couldn't recall the precise syntax of the method reference operator signature.

This lambda is functionally equivalent to
```java
Comparator.comparingInt(ItemStack::getCount)
```

File: src/main/java/gregtech/api/util/InventoryUtils.java (hunk 5 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/util/InventoryUtils.java]: This has been done.

File: src/main/java/gregtech/api/util/InventoryUtils.java (hunk 4 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/util/InventoryUtils.java]: This has been done.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 8 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java]: This has been done. The logic in addItemsToItemHandler has been adjusted to call the new method logic, and the simulate case from the original addItemsToItemHandler method is also handled.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 7 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java]: As mentioned on discord, this is currently not a bug due to the logic of getAllItemOutputs truncating the number of outputs to the maximum number of slots. This should probably be looked at more in depth in a different issue to make sure that all consequences of changing it, if that is what is desired, are handled.

File: src/main/java/gregtech/api/util/InventoryUtils.java (hunk 6 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/util/InventoryUtils.java]: There has been some attempt to make the logic here clearer.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 7 above)
Comment (LAGIdiot) [reply src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java]: Yeah we can skip this one here and follow up on it in #1215

File: src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiFurnace.java [hunk 9]
```diff
@@ -166,4 +203,46 @@ protected Recipe findRecipe(long maxVoltage, IItemHandlerModifiable inputs, IMul
...
+            }
+
+            // if there is a partial stack, add it too
+            if(remainder > 0) {
+                ItemStack partial = outputStack.copy();
+                partial.setCount(remainder);
+                recipeOutputs.add(partial);
+            }
+        }
+    }
```
Comment (LAGIdiot) [inline src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiFurnace.java:246]: Move this to `MultiFurnaceWorkable` as only that inner class is using it.

**Review by LAGIdiot — CHANGES_REQUESTED** [review]
Thank you for updating this PR. There is only one last thing that need to get fixed.

Also I think that comments in some cases are quite extensive and not necessary as what is going on can be picked from code (like max items allowed in a stack) or documentation comment for private functions. But there is no need to do anything about it.

File: src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiFurnace.java (hunk 9 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiFurnace.java]: This has been done.

**Review by LAGIdiot — APPROVED** [review]
Good work finishing it up.
